image: gitpod/workspace-full-vnc

tasks:
   - name: SUDOs
   - before: sudo apt-get update && \
        sudo apt-get install -y libx11-dev libxkbfile-dev libsecret-1-dev libgconf2–4 libnss3 && \
        sudo rm -rf /var/lib/apt/lists/*
